#!/usr/bin/env bash

BOOST_VERSION=1.57.0
SQLITE_VERSION=3.8.8.1
LIBUV_VERSION=1.4.0
ZLIB_VERSION=system
NUNICODE_VERSION=1.5.1
LIBZIP_VERSION=0.11.2

export MASON_ANDROID_ABI=${MASON_PLATFORM_VERSION}
